name: Build Book
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build deps
        run: pip install markdown pyyaml

      - name: Build
        run: python scripts/build.py

      - name: Commit built book.html
        run: |
          if [[ -n "$(git status --porcelain dist/book.html)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add dist/book.html
            git commit -m "chore: build book [skip ci]"
            git push
          fi
